[[cards]]
prefab_id = 1104

[cards.scene_param]
instance_id = "1104-血滴-198837ef-1214-4b80-9217-ce4aa8ab59d2"
position = [
    483.0,
    63.0,
]
rotation = 0.0
order = 1.0
description = "title: 血滴, image_path: pic/blood-drop.png, desc: 血滴（线索）"

[cards.runtime_specialized_param]
type = "clue"

[cards.runtime_specialized_param.params.target_card_param]
prefab_id = 1904

[cards.runtime_specialized_param.params.target_card_param.scene_param]
instance_id = "1904-对话交互卡-1c1ff64b-9355-46c8-bbfa-0c65e60326b1"
order = 2.0
position = [
    502.0,
    -150.0,
]
rotation = -0.0
